# image softwarecraftsmen/postgresql-data
FROM ubuntu:14.04.1

MAINTAINER Martin Ahrer <martin.ahrer@gmail.com>

# Add VOLUMEs to allow backup of config, logs and databases
VOLUME  ["/etc/postgresql", "/var/log/postgresql", "/var/lib/postgresql", "/var/run/postgresql"]

CMD ["true"]
