# image softwarecraftsmen/postgresql-server-fhs
FROM localhost:5000/softwarecraftsmen/postgresql-server:9.3-13
MAINTAINER Software Craftsmen GmbH und CoKG <office@software-craftsmen.at>

ADD create-database.sql /etc/softwarecraftsmen/postgresql/docker-entrypoint-initdb.d/